import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import { SessionProvider, RolesInfo, NullSession } from "./sessionCC";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const getRoles = async (): Promise<RolesInfo> => {
  const apiServer = process.env['services__webapi__1']
  const request: Response = await fetch(`${apiServer}/api/auth/roles`, { cache: 'no-cache' })
  if (request.ok) {
    return await request.json()
  }
  return {}
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rolesInfo = await getRoles()

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider rolesInfo={rolesInfo}>
          <Header></Header>
          <div className="main">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}



