import type { Metadata } from "next"
import { Inter, Fira_Mono } from "next/font/google"
import "./globals.scss"

import { SessionProvider, RolesInfo, NullSession } from "../context/session"
import Header from "../components/header/header"

const inter = Inter({ subsets: ["latin"] })

const firaMono = Fira_Mono({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--fira-mono'
})

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

const getRoles = async (): Promise<RolesInfo> => {
  const apiServer = process.env['services__webapi__1']
  const request: Response = await fetch(`${apiServer}/api/auth/roles`, { cache: 'no-cache' })
  if (request.ok) {
    return await request.json()
  }
  return {}
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const rolesInfo = await getRoles()

  return (
    <html lang="en">
      <body className={`${inter.className} ${firaMono.variable}`}>
        <SessionProvider rolesInfo={rolesInfo}>
          <Header></Header>
          <div className="main">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}



